### ISSUE TITLE
how to make gts message format according to WMO No. 386 Manual on the Global Telecommunication System - Part II - Operational Procedures for the GTS. 

### ISSUE THREAD

**Issue by engshara** [wmo-im/GTStoWIS2#100] opened 2022-07-28 02:46 UTC
how to make gts message format according to WMO No. 386 Manual on the Global Telecommunication System - Part II - Operational Procedures for the GTS. 
i want to send my bulletin but i must to convert the message to gts format and send it using sftp so how can i get it ?

**Comment by petersilva** [comment] 2022-07-28 13:57
This project is part of trying to nudge people along from really old obsolete GTS to  WIS2 (the new WMO target exchange mechanism.) 

Are your bulletins big? if they are small,  perhaps post an example? 

If "convert message to gts format" I think you mean putting an abbreviated header line (AHL) on the top of it?  when people talk about "bulletins" they typically already are in GTS format (from WMO 306) ... I imagine the only thing missing for WMO 386 is a header (AHL.)

If you don't have a bulletin with an AHL, the normal way to get add an AHL is to get your bulletin ingested into a WMO switch.  This module is not concerned with assigning AHL's as that is considered a legacy problem.  Part of the problem is that AHL's are actually assigned by hand using tables.  There isn't any possible code to build them as there are choices involved, where you just need to know what that GTS switch administrator decided.

so the next step depends on:  

Are you trying to be fully modern native WIS2 data?  
   - in that case, I would probably direct your to wis2box, and we can see how to accept
     your data in a native WIS2 method, where there would be no such thing as a GTS header.

Or are you just trying to make old data available as easily a possible?
   - This is the case this repository is concerned with, we add some logic to take
     and existing GTS message (that already has a header) and post that in WIS2
     in a way that makes it accessible (but missing a lot of features that would be
     present in a WIS2 approach above.)
  - before we can apply this repository's code, you need to have a bulletin
   with a valid GTS AHL, and that would be assigned by a member state's 
   GTS adminisatrator.

**Comment by engshara** [comment] 2022-07-29 01:26
dear peter

i like to give you these information about wmo message :
WMO MessageStructure :  

Message Components : The format of meteorological messages is:
   
   - A starting line
   - An abbreviated heading line
   - Text (body of bulletin)
   - An end-of-message signal.
so , as you know what is the wmo message contents , i like to have script that convert the bulletin to wmo message structure. so can you help me to have this script ?    On Thursday, July 28, 2022 at 04:58:06 PM GMT+3, Peter Silva ***@***.***> wrote:  
 
 


This project is part of trying to nudge people along from really old obsolete GTS to WIS2 (the new WMO target exchange mechanism.)

Are your bulletins big? if they are small, perhaps post an example?

If "convert message to gts format" I think you mean putting an abbreviated header line (AHL) on the top of it? when people talk about "bulletins" they typically already are in GTS format (from WMO 306) ... I imagine the only thing missing for WMO 386 is a header (AHL.)

If you don't have a bulletin with an AHL, the normal way to get add an AHL is to get your bulletin ingested into a WMO switch. This module is not concerned with assigning AHL's as that is considered a legacy problem. Part of the problem is that AHL's are actually assigned by hand using tables. There isn't any possible code to build them as there are choices involved, where you just need to know what that GTS switch administrator decided.

so the next step depends on:

Are you trying to be fully modern native WIS2 data?
   
   - in that case, I would probably direct your to wis2box, and we can see how to accept   
your data in a native WIS2 method, where there would be no such thing as a GTS header.

Or are you just trying to make old data available as easily a possible?
   
   - This is the case this repository is concerned with, we add some logic to take   
and existing GTS message (that already has a header) and post that in WIS2   
in a way that makes it accessible (but missing a lot of features that would be   
present in a WIS2 approach above.)
   - before we can apply this repository's code, you need to have a bulletin   
with a valid GTS AHL, and that would be assigned by a member state's   
GTS adminisatrator.

**Comment by petersilva** [comment] 2022-07-29 12:11
Hi @engshara ,

Do you already have a header to put in your WMO message ?  Can you provide such a header as an example?  We can't make it up, it isn't based only on the content, but includes information you must obtain from a GTS routing administrator.  There is no program that can determine a full WMO 386 header.  You need the content AND the header as an input, or you need to feed content to a GTS switch which an administrator has configured with the necessary decisions (tables made up by the admin.) to assign a header.

The work here assumes GTS messages (that already have a WMO 386 (aka GTS) header) If your data does not have a header, the code here is not helpful to you.

Discussion is generally much easier with examples.  if you could provide some, I might be able to provide better hints.

**Comment by petersilva** [comment] 2022-07-29 12:17
An AHL starts with TTAAii... where ii are numbers between 0 and 99, and there is some scope, but generally the GTS admin 
 picks a number.  We can guess, but we have a small percentage probability of being correct.  The ii, in Canada, for example, for surface observations, is based on the list of grouping of observations sites assigned to a each number.  It's a table only the GTS admin of each country has.  The countries don't provide that mapping internationally.

Perhaps they should!  but today they don't, so there is no way to assign ii correctly in a header from only the message content.

**Comment by petersilva** [comment] 2022-11-01 10:43
if there is further information required this issue can be re-opened.

**Closed by petersilva** 2022-11-01 10:43 UTC
