### ISSUE TITLE
MQP topic structure

### ISSUE THREAD

**Issue by kurt-hectic** [wmo-im/GTStoWIS2#9] opened 2020-11-30 11:31 UTC
How should the MQP topic structure look like? Where and how can be it formally specified?

**Comment by petersilva** [comment] 2021-01-07 21:55
Please clone this repository, follow the instructions in the README.  The GTStoWIS2 python routines and accompanying JSON tables implement a topic structure, by mapping all the GTS tables A->D to a topic tree.

**Comment by petersilva** [comment] 2021-01-08 22:10
I think there is a topic structure proposed by this repository.  Whether it is accepted or not... Antje and I are still iterating on it... we are not even presenting it yet.  I guess keep it open for now.

**Comment by josusky** [comment] 2021-01-29 09:48
@petersilva , I suppose that @kurt-hectic was looking behind the GTS data identified by AHL. Converting the TTAAii CCCC is important step to get things moving but we need to take into account other types of data too. 
It might be too early for it but at some point we should publish the (topic) tree in a user friendly way so that producers of (non-bulletin-like) data can look at it and decide what is the right topic for their products. And we will need a mechanism how to maintain the tree - add/remove branches and leaves to adjust it to the new data. 
I think, that this would be then a task for some future team, we just need to think about a form in which we could pass the initial tree to this other team and to the wider community.

**Comment by petersilva** [comment] 2021-01-29 15:36
@kurt-hectic if you checkout the module, and run python3 test.py... you will see a list of a few hundred TTAAii's together with the mappings.  @antje-s has expanded all the possibilities in the table, and I think it went into millions of lines, so just producing an exhaustive list is probably not helpful for people to understand it.

**Comment by petersilva** [comment] 2021-01-30 18:03
In the 20210130 TT meeting, @davidpodeur brought up versioning in the discussion of #8 (message format). @josusky aptly recapitulated what had been discussed in the previous meetings, that the topic hierarchy includes a version tag.  In the Canadian stack, this works out to a *topic_prefix* like _v03.post_  (amqp) or (v03/post) (mqtt). Others have had objections to the topic prefix as a whole,
and in particular the inclusion of "post".  Origin of "post": In earlier iterations (v02) of the Canadian stack, there were multiple message formats:

* a "post" format,to announce new files.
* a "report" format which was for consumers to return telemetry back to publishers (sort of WMO Monitoring?) 

the subtopic after the version key identified the message format. In v03, the report format just becomes fields in a v03 message (as in #22) so there is no need for a topic to separate it out, and I guess "post" could be dropped.  In order to have a scheme that works with MQTT and AMQP, as per the WMO mesh protoype. one would use the top level topic as an "exchange".

So, take a message, such as:

* YMAC13_KWEC_211300_4d31f6baa5bb36a40f60d027ec4d7af0.grib
```
fractal% python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import GTStoWIS2
>>> topic_mapper=GTStoWIS2.GTStoWIS2()
>>> topic_mapper( 'YMAC13_KWEC_211300_4d31f6baa5bb36a40f60d027ec4d7af0.grib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'GTStoWIS2' object is not callable
>>> topic_mapper.mapAHLtoTopic( 'YMAC13_KWEC_211300_4d31f6baa5bb36a40f60d027ec4d7af0.grib')
'us/KWEC/model-regional/national/0-90n/0-90w/06h'
```
so using the module, we map the TTAAii CCCC to a sub topic tree: us/KWEC/model-regional/national/0-90n/0-90w/06h
We also need a topic prefix:  v03
In AMQP, one would have an exchange name. The exchange name can be anything, but we just picked a convention of *xpublic*... in the Canadian stack.  it should be upto each node to pick their preferred exchange.

n MQTT, use that as the root of the topic tree.

So the full topic:

* for MQTT is:  xpublic/v03/us/KWEC/model-regional/national/0-90n/0-90w/06h
* for AMQP is (on the xpublic exchange): v03.us.KWEC.model-regional.national.0-90n.0-90w.06h

Does this sound like something that folks would agree on?

**Comment by petersilva** [comment] 2021-01-30 18:07
oh... and why is having the AMQP exchange name mapped to the root of the topic tree in MQTT? 
because in AMQP exchanges are used to identify different audiences, and permissions are granted to particular exchanges.  Similarly, in MQTT brokers, permissions would be assigned to parts of the topic tree, so having a common root for each purpose helps with setting permissions up.

**Comment by petersilva** [comment] 2021-02-18 12:26
I forgot about the date... we always have a date in our structure...  So we have a complete retrieval URL that is:

http://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/20210218/WIS/ba/sarajevo_nmc/observation/surface/land/fixed/synop/main/0-90n/90e-0

The baseURL is: https://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/

so the directory tree is: 20210218/WIS/ba/sarajevo_nmc/observation/surface/land/fixed/synop/main/0-90n/90e-0

The AMQP topic is: v03.20210218.WIS.ba.sarajevo_nmc.observation.surface.land.fixed.synop.main.0-90n.90e-0

The MQTT topic is prefixed by the AMQP exchange (usually xpublic, but here more custom):
xs_pas037_wmo_sketch_public/v03/20210218/WIS/ba/sarajevo_nmc/observation/surface/land/fixed/synop/main/0-90n/90e-0

file name in the topic folder is:
ISMD01_LQSM_181200_b04e4bb15e6c18e975e1020583da946d.bufr

**Comment by josusky** [comment] 2021-02-19 14:23
I guess we have had this discussion before, but I am not sure if we have concluded it somehow, so let me note it again.
It is clear why the date is in the path but it does not need to be in the topic. No one is going to subscribe to data from yesterday - the data could be there but most likely there would not be any new notification for the previous day. Of course, one can always put there a wildcard - but why? We have dropped hour part (which is valid on any day) so let's drop the date too. A topic like:
`v03.WIS.ba.sarajevo_nmc.observation.surface.land.fixed.synop.main.0-90n.90e-0`
perfectly serves the purpose of advertising files like:
[http://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/20210218/WIS/ba/sarajevo_nmc/observation/surface/land/fixed/synop/main/0-90n/90e-0/SMD01_LQSM_181200_b04e4bb15e6c18e975e1020583da946d.bufr]

**Comment by petersilva** [comment] 2021-02-19 14:28
OK.. but if we do that, then the application has "magic" where someone has to intuit the correct day... which near the border between days, is accident prone... Perhaps the thing to do is move the date into the baseURL field.  That way the baseURL will change every day, but the topic will omit the dates as desired.

**Comment by josusky** [comment] 2021-02-19 14:53
@petersilva No, there is no need for any heuristics. The application subscribes to a fixed topic and receives notification that yield fully qualified URL for download.

**Comment by petersilva** [comment] 2021-02-20 17:33
ok, on the issue009 branch, I merged in issue005 branch (removing interpretation of C4, and C4 (forecast hours) from topic tree)
and then added a   genTableTTAAii(self) routine to the GTStoWIS2 class.

so I can create the table with:
````
    import GTStoWIS2
    import json
    t=GTStoWIS2.GTStoWIS2()
   t.genTableTTAAii()
   f=open("tableTTAAii.json","w")
   f.write( json.dumps( t.tableTTAAii, indent=2 ) )
   f.close()

````
github doesn't want me attaching 300KB jsons... but you can reproduce it.

**Comment by antje-s** [comment] 2021-02-22 06:50
> 
> 
> @petersilva No, there is no need for any heuristics. The application subscribes to a fixed topic and receives notification that yield fully qualified URL for download.

... so the date would be part of the baseUrl value of the message (added to the fixed baseURL part) - that sounds ok to me

**Comment by petersilva** [comment] 2021-03-18 12:13
merging, blessed at meeting, closing.

**Comment by petersilva** [comment] 2022-07-13 10:43
deferring to: https://github.com/wmo-im/wis2-topic-hierarchy

**Closed by petersilva** 2022-07-13 10:43 UTC
Labels: Decision, blocker
